name: Sync Release to Main

on:
  schedule:
    # 每隔7小时运行一次（UTC时间）
    - cron: '0 */7 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: release
          path: release

      - name: Copy Release to Main's Rule Folder
        run: |
          # 删除 main 分支的 rule 文件夹（如果存在）
          #rm -rf main/rule
          # 创建 rule 文件夹
          #mkdir -p main/rule
          # 复制 release 分支的所有内容到 main/rule
          cp -rf release/* main/rule/

      - name: Commit and Push Changes
        run: |
          cd main
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore: sync release branch to main/rule [automated]"
          git push
